a = int(input())
count = 0
last = a % 10
first = 0
composition = 1
total = 0
while a != 0:
    if a != 0:
        count += 1
        composition *= a % 10
    first = a % 10
    total = first + total
    a = a // 10
first_last = first + last
average = total / count
print(total, count, composition, average, first, first_last, sep='\n')
